version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - back-tier

  server:
    build: ./server
    expose:
      - "5000"
    # ports:
    #   - "5000:5000"
    networks:
      back-tier:
        aliases:
          - flask-app

  client:
    build: ./client
    expose:
      - "3000"
    # ports:
    #   - "5000:5000"
    networks:
      back-tier:
        aliases:
          - react-app

networks:
  back-tier: