version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./data/local/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - back-tier

  server:
    container_name: flask_server
    build: ./server
    volumes:
      - ./server:/app
    expose:
      - "5000"
    # ports:
    #   - "5000:5000"
    networks:
      back-tier:
        aliases:
          - flask-app

  client:
    container_name: react_client
    build: ./client
    volumes:
      - ./client/src:/usr/src/app/src
    expose:
      - "3000"
    # ports:
    #   - "5000:5000"
    networks:
      back-tier:
        aliases:
          - react-app

networks:
  back-tier: