version: '3'
services:

  server:
    container_name: flask_server
    build: ./server
    expose:
      - "5000"
    networks:
      back-tier:
        aliases:
          - flask-app

  client:
    container_name: react_client
    build: ./client
    expose:
      - "3000"
    networks:
      back-tier:
        aliases:
          - react-app


  nginx: 
    depends_on:
      - client
      - server
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - back-tier

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
  back-tier: